---
title: "BREAKING NEWS: FBI says they found 'Man Child' in the woods!"
description: |
  Dangerous 'Man Child' on the loose. 
author:
  - name: Sophia Zhu 
    url: https://github.com/zhusophia
    affiliation: New Hork Times

date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### "It was nothing like I have ever seen before.... It's absolutely horrifying! 

Horton, T.M - In what way would you expect to see a so-called “Man Child”, as prayed by the FBI, appear on your doorstep? This was the day of Joseph Joestar, who stepped out of his house, having his porch steps stolen, and all that was left was a giant footstep in the dirt. 

Thus, he decided to check hsi cameras, where it was then spotted that there was a strange creature that showed up to the doro at the middle of the night, barely five foot tall, yet walking witht ehs speed and confidence of an adult supermodel. As the FBI agent that he was, he sprang into action. He immediately contacted the headwaters, and brought along the footage of this person to investigate. As the technology at the FBI headquarters enlarged the photo, one, twice, and then five times to figure out the identity of the person… It was the face of a man. With the  body of a child. 

#### “I distinctly remember the second I saw the image. I was in SHOCK! I mean, who would have imagined something like this could actually exist?” 

says an FBI agent, shaking their head in awe. “I’d love to try and see what happened for them to get to this state.” 

As the FBI compensated Joestar for his porch, they swore to never speak out this again, unless it struck another time, and that it did. 

When Joestar arrived back at his house, after visiting the headquarters, he was at a loss. He blinked in confusion, looked around him, and realized…. His ENTIRE house was gone! He quickly snapped a shot of the empty plot of land, nothing remaining except for a few rocks, and the soily ground. He had to be dreaming right? 

As he failed the FBI number again, something shiny in the woods caught his eye. He glanced at it, rubbed his eyes to make sure he wasn’t hallucinating, then proceeded towards the woods cautiously. He passed through brambles, a grove, the small river that just had the tiniest bit of water still trickling. He glanced around. EVerything seemed normal around here. He nods his head, before heading back to his plot of land, and flopped down on his back out of exhaustion. As he was about to drift off to sleep, he heard faint noises calling him… was someone saying his name? 

He sprung up, glancing around the nearby vicinity, before realizing it was his phone! He had forgotten to hang up when he went into the woods. As he apoligzed, and continued discussing the situation, all of a sudden, a pink man sprinted towards him, darting faster than he would ever think would be possible. 

Joseph's instincts saved him ,as he darted out of the way, before throwing a punch at the intruder, which just barely missed him. The pink man glanced at Joseph, on the ground, adrenaline pumping, the man shrugged then left back into the woods. 

#### “MAN CHILDDDDD” Joseph screams. “GIVE ME BACK MY HOUSE.”

The pink man reappeared, shook his head no, before returning to the woods. What an eventful day it must have been for Joestar, and what a raise he’d be getting by reporting this to the FBI. 


